title = "Lazada Mobile Style Guides"
languagecode = "en_US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false

baseurl = "https://lzd-ux.github.io/styleguide"

relativeurls = false
canonifyurls = true
watch = true

[author]
  name = "Lazada UX Team"

[params]
  Description = "This guide groups most used interaction design pattenrs and explain how to implement them to help creating mobile experiences for Lazada products."

[taxonomies]
  category = "categories"
  tag = "tags"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]
